# Generated by Django 6.0.2 on 2026-02-06 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('domain', models.CharField(help_text='Primary domain associated with this organization', max_length=255, unique=True, verbose_name='Domain')),
                ('logo', models.FileField(blank=True, help_text='Organization logo. Recommended size: 200x200 pixels', null=True, upload_to='organizations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'svg'], message='Only image files (JPG, PNG, GIF, SVG) are allowed')], verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'indexes': [models.Index(fields=['domain'], name='core_organi_domain_075917_idx'), models.Index(fields=['is_active'], name='core_organi_is_acti_9518a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique identifier for the department', max_length=50, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee_id', models.CharField(blank=True, help_text='Organization-specific employee identifier', max_length=50, null=True, unique=True, verbose_name='Employee ID')),
                ('phone_number', models.CharField(blank=True, help_text='Format: +1234567890', max_length=20, verbose_name='Phone Number')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('avatar', models.FileField(blank=True, help_text='Profile picture. Recommended size: 150x150 pixels', null=True, upload_to='avatars/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'], message='Only image files (JPG, PNG, GIF) are allowed')], verbose_name='Avatar')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Unique identifier from external identity provider', max_length=255, verbose_name='External ID')),
                ('identity_provider', models.CharField(choices=[('local', 'Local Authentication'), ('google', 'Google'), ('facebook', 'Facebook'), ('azuread', 'Microsoft Azure AD'), ('okta', 'Okta'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('oidc', 'Generic OIDC'), ('saml', 'SAML')], db_index=True, default='local', max_length=50, verbose_name='Identity Provider')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Login At')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the user has verified their email address', verbose_name='Email Verified')),
                ('mfa_enabled', models.BooleanField(default=False, help_text='Whether multi-factor authentication is enabled', verbose_name='MFA Enabled')),
                ('preferred_language', models.CharField(default='en', help_text='Language code (e.g., en, es, fr)', max_length=10, verbose_name='Preferred Language')),
                ('timezone', models.CharField(default='UTC', help_text='User timezone (e.g., America/New_York)', max_length=50, verbose_name='Timezone')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='core_depart_code_5a5745_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization'], name='core_depart_organiz_64c6f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_department_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['employee_id'], name='core_userpr_employe_7133ad_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['external_id', 'identity_provider'], name='core_userpr_externa_4ae3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['identity_provider'], name='core_userpr_identit_0e3744_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email_verified'], name='core_userpr_email_v_2a8633_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department'], name='core_userpr_departm_ea531d_idx'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id', 'identity_provider'), name='unique_external_identity'),
        ),
    ]
