# Generated by Django 6.0.2 on 2026-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata for profile', null=True, verbose_name='Extra Data'),
        ),
    ]
