# Generated by Django 6.0.2 on 2026-04-11 00:57

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='advocate_document',
            field=models.FileField(blank=True, help_text='Licensed proof document (PDF or image). Max file size: 5MB', null=True, upload_to='advocate_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif'], message='Only PDF and image files (JPG, PNG, GIF) are allowed')], verbose_name='Advocate Document'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bar_id',
            field=models.CharField(blank=True, help_text='Licensed Bar/License ID number for advocates', max_length=50, null=True, verbose_name='Bar ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('advocate', 'Advocate'), ('party_in_person', 'Party in Person')], db_index=True, default='party_in_person', help_text='Classification of user: Advocate or Party in Person', max_length=20, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +1234567890 or 1234567890', max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone_number'], name='core_userpr_phone_n_691ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_type'], name='core_userpr_user_ty_baccfd_idx'),
        ),
    ]
