# Generated by Django 6.0.2 on 2026-04-06 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplicationExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trusted_resource_server', models.BooleanField(default=False, help_text='Allow this client to introspect tokens issued to any other registered client (resource-server role, RFC 7662).')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='OAuth application')),
            ],
            options={
                'verbose_name': 'Application extension',
                'verbose_name_plural': 'Application extensions',
            },
        ),
    ]
