# Generated by Django 6.0.2 on 2026-02-06 10:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0017_usersocialauth_user_social_auth_uid_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google-oauth2', 'Google'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('microsoft-graph', 'Microsoft'), ('linkedin', 'LinkedIn'), ('azuread-oauth2', 'Azure AD'), ('okta-oauth2', 'Okta'), ('openid-connect', 'Generic OIDC'), ('twitter', 'Twitter'), ('apple-id', 'Apple ID'), ('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=50, verbose_name='Provider')),
                ('provider_id', models.CharField(db_index=True, help_text='Unique identifier from the social provider', max_length=255, verbose_name='Provider User ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address from the social provider', max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, help_text='Full name from the social provider', max_length=255, verbose_name='Full Name')),
                ('picture_url', models.URLField(blank=True, help_text="URL to the user's profile picture", max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Profile Picture URL')),
                ('access_token', models.TextField(blank=True, help_text='OAuth2 access token (should be encrypted in production)', verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth2 refresh token (should be encrypted in production)', verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, help_text='When the access token expires', null=True, verbose_name='Token Expiry')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific data in JSON format', verbose_name='Extra Data')),
                ('scopes', models.TextField(blank=True, help_text='Granted OAuth scopes (space-separated)', verbose_name='OAuth Scopes')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary social connection for the user?', verbose_name='Is Primary')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this connection currently active?', verbose_name='Is Active')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Connected At')),
                ('last_used', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Used')),
                ('last_synced', models.DateTimeField(blank=True, help_text='When profile data was last synced from the provider', null=True, verbose_name='Last Synced')),
                ('social_auth', models.OneToOneField(blank=True, help_text='Link to social_django UserSocialAuth model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_info', to='social_django.usersocialauth', verbose_name='Social Auth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Social Connection',
                'verbose_name_plural': 'Social Connections',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='social_soci_user_id_ad0681_idx'), models.Index(fields=['provider', 'email'], name='social_soci_provide_1318f3_idx'), models.Index(fields=['connected_at'], name='social_soci_connect_aa1ca1_idx')],
                'unique_together': {('provider', 'provider_id')},
            },
        ),
        migrations.CreateModel(
            name='SocialLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('connect', 'Connect New Account'), ('disconnect', 'Disconnect Account'), ('token_refresh', 'Token Refresh'), ('error', 'Error')], db_index=True, default='login', max_length=20, verbose_name='Event Type')),
                ('provider', models.CharField(choices=[('google-oauth2', 'Google'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('microsoft-graph', 'Microsoft'), ('linkedin', 'LinkedIn'), ('azuread-oauth2', 'Azure AD'), ('okta-oauth2', 'Okta'), ('openid-connect', 'Generic OIDC'), ('twitter', 'Twitter'), ('apple-id', 'Apple ID'), ('slack', 'Slack'), ('discord', 'Discord')], db_index=True, max_length=50, verbose_name='Provider')),
                ('provider_id', models.CharField(blank=True, help_text='User ID from the social provider', max_length=255, verbose_name='Provider User ID')),
                ('email_attempted', models.EmailField(blank=True, help_text='Email address used in the authentication attempt', max_length=254, verbose_name='Email Attempted')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Success')),
                ('error_code', models.CharField(blank=True, help_text='Error code if authentication failed', max_length=100, verbose_name='Error Code')),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message if authentication failed', verbose_name='Error Message')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='HTTP User-Agent header from the request', verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, help_text='HTTP Referer header', verbose_name='Referer')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional context data in JSON format', verbose_name='Extra Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('duration_ms', models.IntegerField(blank=True, help_text='How long the authentication took in milliseconds', null=True, verbose_name='Duration (ms)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_login_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Social Login Event',
                'verbose_name_plural': 'Social Login Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['success', 'created_at'], name='social_soci_success_021b62_idx'), models.Index(fields=['provider', 'created_at'], name='social_soci_provide_2c168d_idx'), models.Index(fields=['email_attempted', 'created_at'], name='social_soci_email_a_7bb97b_idx')],
            },
        ),
    ]
